
version: '3'
services:
    codecept:
        image: codeception/codeception:3.1.0
        container_name: codeception
        volumes:
            - ../tests:/project
        networks:
            - codeception
        environment:
            - TEST_URL=http://omartin.es/
        depends_on:
            - selenium-chrome
    selenium-chrome:
        image: selenium/standalone-chrome-debug:3.141.59
        container_name: selenium-standalone-chrome
        ports:
            - 5900:5900
            - 4444:4444
        dns: 8.8.4.4
        networks:
            - codeception
        environment:
            - no_proxy=localhost
            - TEST_URL=http://omartin.es/

networks:
    codeception:
        driver: bridge
